name: world-happiness-model-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas>=1.3.0
  - numpy>=1.19.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - scikit-learn>=0.24.0
  - jupyter>=1.0.0
  - geopandas>=0.9.0
  - plotly>=5.1.0
  - tensorflow>=2.6.0
  - pip